root-mrrobot/SD-Project

Home.java
=> Created Home.java

app/src/main/java/com/example/myapplication/Register.java, app/src/main/java/com/example/myapplication/User.java
Changed database to show password, added a todo for email authentication for register page.
=> Changed user to show password in database instead of age

app/src/main/java/com/example/myapplication/Home.java, app/src/main/java/com/example/myapplication/Register.java, app/src/main/java/com/example/myapplication/SplashScreen.java, app/src/main/java/com/example/myapplication/User.java
Commented  to user, register, splash screen, home java files
=> Added Comments

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/myapplication/Login.java, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/strings.xml
Added functions to deal with if a user forgets there password. Can recover it via an email reset password link sent to there email
=> Forgot password functionality

app/src/main/java/com/example/myapplication/Account.java, app/src/main/java/com/example/myapplication/Home.java, app/src/main/java/com/example/myapplication/Register.java, local.properties
Commented functions, took out dependencies not needed
=> added additional comments

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/myapplication/Home.java, app/src/main/java/com/example/myapplication/LecturerAccountFragment.java, app/src/main/java/com/example/myapplication/LecturerCoursesFragment.java, app/src/main/java/com/example/myapplication/LecturerHomeFragment.java, app/src/main/java/com/example/myapplication/LecturerNavigation.java, app/src/main/java/com/example/myapplication/StudentNavigation.java, app/src/main/res/drawable/ic_baseline_library_courses_24.xml, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_lecturer_navigation.xml, app/src/main/res/layout/fragment_lecturer_account.xml, app/src/main/res/layout/fragment_lecturer_courses.xml, app/src/main/res/layout/fragment_lecturer_home.xml, app/src/main/res/menu/lecturer_navigation_menu.xml
Added in the navigation bar for the lecturer interface and the templates for the associated fragments.
=> Added lecturer navigation bar and templates for fragments

app/src/androidTest/java/com/example/myapplication/RegisterTest.java
Implemented negative test cases for Register Activity.
=> Added additional Test Cases for Register Activity

.idea/misc.xml, app/src/main/java/com/example/myapplication/Course.java, app/src/main/java/com/example/myapplication/StudentCoursePopUp.java, app/src/main/java/com/example/myapplication/StudentHomeFragment.java, app/src/main/res/layout/student_course_pop_up.xml, app/src/main/res/values/strings.xml, local.properties
Added functionality to drop down menu in Student Home Fragment. Added random rating and set up rating bar to display.
=> Sort by Category and Rating

.idea/libraries/Gradle__androidx_exifinterface_exifinterface_1_2_0_aar.xml, .idea/libraries/Gradle__com_github_bumptech_glide_annotations_4_12_0.xml, .idea/libraries/Gradle__com_github_bumptech_glide_disklrucache_4_12_0.xml, .idea/libraries/Gradle__com_github_bumptech_glide_gifdecoder_4_12_0_aar.xml, .idea/libraries/Gradle__com_github_bumptech_glide_glide_4_12_0_aar.xml, .idea/libraries/Gradle__com_google_firebase_firebase_storage_17_0_0_aar.xml, .idea/libraries/Gradle__com_google_firebase_firebase_storage_20_0_1_aar.xml, .idea/misc.xml, .idea/modules/app/My_Application.app.iml, app/build.gradle, app/src/main/java/com/example/myapplication/LecturerCoursesFragment.java, app/src/main/java/com/example/myapplication/LecturerData.java, app/src/main/java/com/example/myapplication/LecturerHomeFragment.java, app/src/main/java/com/example/myapplication/Model.java, app/src/main/java/com/example/myapplication/info_courses.java, app/src/main/res/layout/activity_info_courses.xml, app/src/main/res/layout/fragment_lecturer_courses.xml, app/src/main/res/layout/fragment_lecturer_home.xml
image uri is now stored in realtime database for easy access.
=> Updated functionality on image retrieval

.idea/misc.xml, .idea/modules/app/My_Application.app.iml, app/build/generated/source/buildConfig/androidTest/debug/com/example/myapplication/test/BuildConfig.java, app/src/androidTest/java/com/example/myapplication/LoginTest.java, app/src/androidTest/java/com/example/myapplication/SettingsTest.java, app/src/main/java/com/example/myapplication/LecturerAccountFragment.java, app/src/main/java/com/example/myapplication/Login.java, app/src/main/java/com/example/myapplication/StudentAccountFragment.java, app/src/main/res/layout/activity_settings.xml, local.properties
Added additional Test Cases for Settings and Login Activities.
Implemented nan Alert Dialog on Account activities for Logging out of a user.
=> Added Additional Test Cases

.idea/misc.xml, app/src/androidTest/java/com/example/myapplication/HomeTest.java, app/src/androidTest/java/com/example/myapplication/LoginTest.java, app/src/androidTest/java/com/example/myapplication/RegisterTest.java, app/src/androidTest/java/com/example/myapplication/SettingsTest.java, app/src/androidTest/java/com/example/myapplication/SplashScreenTest.java, app/src/main/res/layout/activity_home.xml, local.properties
Added Test Cases for Splash Screen
=> Added Test Cases 

app/src/androidTest/java/com/example/myapplication/HomeTest.java
Added some more test cases for Home Activity.
=> Added Test Cases for Home

app/src/androidTest/java/com/example/myapplication/LoginTest.java, app/src/androidTest/java/com/example/myapplication/RegisterTest.java, app/src/androidTest/java/com/example/myapplication/SettingsTest.java
Added more Test Cases for Login, Register and Settings Activities.
=> Added Test Cases

app/src/androidTest/java/com/example/myapplication/SettingsTest.java, app/src/main/java/com/example/myapplication/LecturerAccountFragment.java, app/src/main/java/com/example/myapplication/Settings.java, app/src/main/java/com/example/myapplication/StudentAccountFragment.java, app/src/main/java/com/example/myapplication/profilePic_data.java, app/src/main/res/layout/activity_settings.xml
users can now change their profile pictures
=> Added Functionality for Profile Pics

app/src/androidTest/java/com/example/myapplication/Models/UserTest.java, local.properties
Added Test Cases for User Model Getters and Setters Methods.
=> Model Test Cases

app/src/androidTest/java/com/example/myapplication/Models/UserTest.java
=> Added Comment

app/src/main/java/com/example/myapplication/Course.java, app/src/main/java/com/example/myapplication/StudentHomeFragment.java
=> Course constructor added

app/src/androidTest/java/com/example/myapplication/LecturerResourceViewTest.java, app/src/androidTest/java/com/example/myapplication/ScrollLecturerCourseTest.java, app/src/androidTest/java/com/example/myapplication/UploadLecturesTest.java, app/src/androidTest/java/com/example/myapplication/lecUploadPdfTest.java, app/src/main/res/layout/activity_lecturer_resource_view.xml
Added Test Cases for Scroll Lecturer Course.
=> Test Cases

app/src/main/java/com/example/myapplication/Course.java, app/src/main/res/drawable/activity_scroll_lecturer_course.xml
=> added ratings

app/src/main/java/com/example/myapplication/DisplayTopics.java, app/src/main/java/com/example/myapplication/LecturerHomeFragment.java
added notifications and quizzes
=> Updated home and display topics 
